name: Build Apache2 Docker Image
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Build Docker image
        run: docker build -f .github/workflows/docker.apache2 -t apache2:latest .
